version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microbit-zemi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pamtdgbldjoy"
s3_prefix = "microbit-zemi"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
